@USER_ID = 1 

### Login

POST http://localhost:3000/login 
content-type: application/json 

{
    "user": {
        "email": "Sam@gmail.com",
        "password": "password"
    }
}

### Index Lists

GET http://localhost:3000/users/{{USER_ID}}/lists
content-type: application/json

### Index List Invites

GET http://localhost:3000/users/{{USER_ID}}/list_invites
content-type: application/json

### Index Friends

GET http://localhost:3000/users/{{USER_ID}}/friends
content-type: application/json

### Friend Requests

GET http://localhost:3000/users/{{USER_ID}}/friendrequests
content-type: application/json

### Index Items
GET http://localhost:3000/lists/2/items
content-type: application/json 

### Delete Item
DELETE http://localhost:3000/lists/2/items/4
content-type: application/json 

### auth_check
GET http://localhost:3000/auth_check
content-type: application/json

### Index list contributors

GET http://localhost:3000/lists/2/contributions
content-type: application/json

### index friend requests
GET http://localhost:3000/users/1/friendrequests

###

GET http://localhost:3000/users/1